image: maven:3.6.3-jdk-11-slim

pipelines:
   branches:
      develop:
         - step:
            caches:
             - maven
            script:
             - apt-get update -y
             - apt-get install -y git
             - git clone --depth=1 https://bitbucket.org/l2jserver/l2j-server-game.git
             - cd l2j-server-game
             - mvn install -DskipTests
             - cd ..
         - step:
            caches:
             - maven
            script:
             - mvn install
            artifacts:
             - target/*.zip
         - step:
            deployment: Production
            script:
             - pipe: atlassian/ftp-deploy:0.2.3
               variables:
                 USER: $FTP_USER
                 PASSWORD: $FTP_PASSWORD
                 SERVER: $FTP_HOST
                 REMOTE_PATH: $FTP_REMOTE_PATH
                 LOCAL_PATH: 'target/'